### ISSUE TITLE
pod version

### ISSUE THREAD

**Issue by andrei4002** [ColinEberhardt/LinqToObjectiveC#10]
I'm getting the 2.0 version when i try to install using cocoapods, but some functions are not present, like linq_sortDescending. Is the latest version submitted to cocoapods?

**Comment by Pikdays** [comment]
The same question。  @ColinEberhardt

**Comment by ColinEberhardt** [comment]
Sorry for the delay, v2.1.0 has been released to CocoaPods https://cocoapods.org/pods/LinqToObjectiveC
